const products = [
	{
		id: 1,
		name: "Americana",
		category: "burger",
		image: "./src/imgs/burguers/americana.jpg",
		ingredients: [
			"Medallon Premium",
			"Cheddar",
			"Bacon",
			"Huevo Frito",
			"Papas Fritas",
		],
		price: 2300,
	},
	{
		id: 2,
		name: "Chees",
		category: "burger",
		image: "./src/imgs/burguers/chees.jpg",
		ingredients: [
			"Medallon Premium",
			"Cheddar",
			"Cebolla",
			"Lechuga",
			"Tomates",
			"Papas Fritas",
		],
		price: 1700,
	},
	{
		id: 3,
		name: "Doble Nelson",
		category: "burger",
		image: "./src/imgs/burguers/doble-nelson.jpeg",
		ingredients: [
			"Doble Medallon Premium",
			"Cheddar",
			"Bacon",
			"Lechuga",
			"Tomates",
			"Pepinos",
			"Papas Fritas",
		],
		price: 3000,
	},
	{
		id: 4,
		
		name: "Repo",
		category: "burger",
		image: "./src/imgs/burguers/repo.jpg",
		ingredients: [
			"Medallon Premium Pollo",
			"Cheddar",
			"Muzzarela",
			"Bacon",
			"Lechuga",
			"Tomates",
			"Papas Fritas",
		],
		price: 2000,
	},
	{
		id: 5,
		name: "roque",
		category: "burger",
		image: "./src/imgs/burguers/roque.jpg",
		ingredients: [
			"Medallon Premium",
			"Roquefort",
			"Salsa BBQ",
			"Rucula",
			"Papas Fritas",
		],
		price: 2800,
	},
	{
		id: 6,
		name: "Triple Mortal",
		category: "burger",
		image: "./src/imgs/burguers/triple-mortal.jpg",
		ingredients: [
			"Triple Medallon Premium",
			"Muzzarela",
			"Bacon",
			"Lechuga",
			"Huevo Frito",
			"Papas Fritas",
		],
		price: 3300,
	},
	{
		id: 7,
		name: "The Rock",
		category: "beer",
		image: "./src/imgs/beers/black.jpg",
		price: 1000,
	},
	{
		id: 8,
		name: "Honey",
		category: "beer",
		image: "./src/imgs/beers/honey.jpg",
		price: 2300,
	},
	{
		id: 9,
		name: "Golden",
		category: "beer",
		image: "./src/imgs/beers/golden.jpg",
		price: 2300,
	},
	{
		id: 10,
		name: "Stella",
		category: "beer",
		image: "./src/imgs/beers/stella.jpg",
		price: 2300,
	},
	{
		id: 10,
		name: "Heineken",
		category: "beer",
		image: "./src/imgs/beers/heineken.png",
		price: 2300,
	},
];
