const products = [
	{
		id: 1,
		name: "Americana",
		group: "burguer",
		image: "./src/imgs/burguers/americana.jpg",
		ingredients: [
			"Medallon Premium",
			"Cheddar",
			"Bacon",
			"Huevo Frito",
			"Papas Fritas",
		],
		price: 2300,
	},
	{
		id: 2,
		name: "Chees",
		group: "burguer",
		image: "./src/imgs/burguers/chees.jpg",
		ingredients: [
			"Medallon Premium",
			"Cheddar",
			"Cebolla",
			"Lechuga",
			"Tomates",
			"Papas Fritas",
		],
		price: 1700,
	},
	{
		id: 3,
		name: "Doble Nelson",
		group: "burguer",
		image: "./src/imgs/burguers/doble-nelson.jpeg",
		ingredients: [
			"Doble Medallon Premium",
			"Cheddar",
			"Bacon",
			"Lechuga",
			"Tomates",
			"Pepinos",
			"Papas Fritas",
		],
		price: 3000,
	},
	{
		id: 4,
		name: "Repo",
		group: "burguer",
		image: "./src/imgs/burguers/repo.jpg",
		ingredients: [
			"Medallon Premium Pollo",
			"Cheddar",
			"Muzzarela",
			"Bacon",
			"Lechuga",
			"Tomates",
			"Papas Fritas",
		],
		price: 2000,
	},
	{
		id: 5,
		name: "roque",
		group: "burguer",
		image: "./src/imgs/burguers/roque.jpg",
		ingredients: [
			"Medallon Premium",
			"Roquefort",
			"Salsa BBQ",
			"Rucula",
			"Papas Fritas",
		],
		price: 2800,
	},
	{
		id: 6,
		name: "Triple Mortal",
		group: "burguer",
		image: "./src/imgs/burguers/triple-mortal.jpg",
		ingredients: [
			"Triple Medallon Premium",
			"Muzzarela",
			"Bacon",
			"Lechuga",
			"Huevo Frito",
			"Papas Fritas",
		],
		price: 3300,
	},
];
